### ISSUE TITLE
Cannot build this module with Xcode 14.0

### ISSUE THREAD

**Issue by kudrautsau-m** [vouched/vouched-react-native#11]
## Expected Behavior
Build runs successfully.

## Actual Behavior
Build fails with error
`Failed to build module 'VouchedCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)', while this compiler is 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)'). Please select a toolchain which matches the SDK.`

## Steps to Reproduce the Problem

  1. Install React Native Vouched package following [the guide](https://github.com/vouched/vouched-react-native#install).
  1. Try to build the project using Xcode 14.0.
 
## Additional notes

Switching to Swift 5.6.1 toolchain helps with this error, but it causes much more errors with other packages.

## Specifications

  - Package version: 1.1.0
  - Xcode version: 14.0

**Comment by JayLVouched** [comment]
Wanted to reach out on this one, I believe this was due to the bitcode compilation, we did release a version a few weeks ago to address this.

**Comment by JayLVouched** [comment]
But to clarify, 1.5.3 is built using 5.7.1, Thanks for the heads up, definitely appreciated
