### ISSUE TITLE
build not created while install in android

### ISSUE THREAD

**Issue by KashifEno8** [vouched/vouched-react-native#12]
when I install the library then library installs very well but when I install the app in android it shows me meven errr after commenting on them meven then another error is happening in the build file at line 119 "Configuration with the name 'compile' not found." and when I change compile to integration then another error happened at line 119 "Resolving dependency configuration 'implementation' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable
 ('canBeResolved=true') dependency configuration that extends 'implementation' should be resolved." and when I added "canBeResolved(true)" then it say null pointer exception
  kindly fix this issue or tell me how to resolve this issue so that I can implement vouched on my app.

<img width="1361" alt="Screenshot 2022-10-12 at 7 49 26 PM" src="https://user-images.githubusercontent.com/96740223/195368062-e2b3fc73-6226-4dcf-b2d0-0e7c17eb720f.png">

**Comment by JayLVouched** [comment]
Hi there, are you able to build the example and run it?
