### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by hernanaero** [vouched/vouched-react-native#3]
In Xcode 12.5 the library does not compile, so we can not build our app in devices with iOS 14.5.

![image](https://user-images.githubusercontent.com/72928794/116748003-1b88a400-a9d5-11eb-8141-008a659fb724.png)

**Comment by Topstar-web** [comment]
I have the same error.
Please help me now.

**Comment by mdobro** [comment]
Same issue now with XCode 13 and Swift 5.5

**Comment by Topstar-web** [comment]
I used XCode 12.4 and it is working fine now

**Comment by josh-vouched** [comment]
I just ran this today on XCode 13.1 and it appears to be resolved.
