### ISSUE TITLE
Could not GET 'https://dl.bintray.com/vouched/maven/id/vouched/android/vouched-sdk/0.3.1/vouched-sdk-0.3.1.pom'. Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by Goldtek** [vouched/vouched-react-native#4]
Could not GET 'https://dl.bintray.com/vouched/maven/id/vouched/android/vouched-sdk/0.3.1/vouched-sdk-0.3.1.pom'. Received status code 403 from server: Forbidden
 occurs in android in using the latest android studio

**Comment by maykonmichel** [comment]
Same here +1

**Comment by maykonmichel** [comment]
I'm having the same problem and it was solved by manually upgrading the vouched android version at `node_modules/@vouched.id/vouched-react-native/android/build.gradle` line 81 replace with `implementation group: 'id.vouched.android', name: 'vouched-sdk', version: '0.3.5'`

I don't know why exactly this is happening and I'll probably submit a PR with this fix.

**Comment by maykonmichel** [comment]
Fixed in the [latest release](https://github.com/vouched/vouched-react-native/releases/tag/v0.2.3)
