### ISSUE TITLE
Autolink support

### ISSUE THREAD

**Issue by StronkMan** [vouched/vouched-react-native#6]
Is [autolink](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-android) supported? after running `react-native link @vouched.id/vouched-react-native`, it imported `id.vouched.rn.VouchedPackage` to `MainApplication.java` but the import doesn't seems to be used anywhere. 

Is this step necessary? `react-native.config.js` should be included [if autolink is not supported](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-customize-how-autolinking-works-for-my-package). 

Thanks.

**Comment by JayLVouched** [comment]
Thanks for reacjing out, and my apologies on the delay. Yes, currently we require ```react-native link``` to import our package.
